# tap "homebrew/bundle"
# tap "homebrew/cask"
# tap "homebrew/cask-fonts"
# tap "homebrew/core"
# tap "homebrew/services"

# Text editors
# brew "ctags-exuberant"
# brew "markdown"
# brew "vim"

# Terminal Tools
# brew "ack"
# brew "amazon-ecs-cli"
# brew "awscli"
# brew "coreutils"
# brew "fzf"
# brew "git"
# brew "gpg"
# brew "gron"
# brew "hub"
# brew "jq"
# brew "proctools"
# brew "reattach-to-user-namespace"
# brew "the_silver_searcher"
# brew "tmux"
# brew "wget"
# cask "aws-vault"
brew "libyaml"

# Application Dependencies
brew "mise"
cask "1password-cli"
brew "uv" # https://docs.astral.sh/uv/
brew "python@3.13"
# brew "autoconf"
# brew "automake"
# brew "awslogs"
# brew "chruby"
# brew "gcc"
# brew "imagemagick"
# brew "libksba"
# brew "make"
# brew "memcached"
# brew "redis"
# brew "ruby-install"

# Hashicorp Tools
# brew "consul"
# brew "nomad"
# brew "terraform"
# brew "vault"

# Databases
# brew "mysql@8.0"
brew "postgresql@16"

# Javascript
# brew "nvm"
# brew "yarn"
